import { motion } from "motion/react";
import { CheckCircle2, AlertCircle, Lightbulb, Target, ChevronLeft, Download, SpellCheck, LayoutList } from "lucide-react";
import { Button } from "@/components/ui/button";

interface ResumeAnalyzerResultsProps {
  analysis: any;
  onBack: () => void;
}

export function ResumeAnalyzerResults({ analysis, onBack }: ResumeAnalyzerResultsProps) {
  if (!analysis) return null;

  const strengths = Array.isArray(analysis.strengths) ? analysis.strengths : [];
  const gaps = Array.isArray(analysis.gaps) ? analysis.gaps : [];
  const improvements = Array.isArray(analysis.improvements) ? analysis.improvements : [];
  const keywordsFound = Array.isArray(analysis.keywordsFound) ? analysis.keywordsFound : [];
  const keywordsMissing = Array.isArray(analysis.keywordsMissing) ? analysis.keywordsMissing : [];
  const spellingFixes = Array.isArray(analysis.spellingFixes) ? analysis.spellingFixes : [];
  const formattingTips = Array.isArray(analysis.formattingTips) ? analysis.formattingTips : [];

  const handleExport = () => {
    const content = `
RESUME ANALYSIS REPORT
-----------------------
Match Score: ${analysis.matchScore ?? 0}%

OVERALL FEEDBACK:
${analysis.feedback ?? "No feedback provided."}

STRENGTHS:
${strengths.map(s => `- ${s}`).join('\n')}

CRITICAL GAPS:
${gaps.map(g => `- ${g}`).join('\n')}

RECOMMENDED IMPROVEMENTS:
${improvements.map((imp, i) => `${i + 1}. ${imp}`).join('\n\n')}

SPELLING & GRAMMAR FIXES:
${spellingFixes.map(f => `- Change "${f.original}" to "${f.suggested}"`).join('\n') || 'No spelling issues found.'}

FORMATTING & FONT SUGGESTIONS:
${formattingTips.map(t => `- ${t}`).join('\n') || 'No formatting issues identified.'}

KEYWORDS FOUND:
${keywordsFound.join(', ') || 'None'}

KEYWORDS MISSING:
${keywordsMissing.join(', ') || 'None'}

Generated by InterviewAI on ${new Date().toLocaleDateString()}
    `.trim();

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `Resume_Analysis_Report.txt`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="max-w-5xl mx-auto px-6 py-32"
    >
      <button 
        onClick={onBack}
        className="flex items-center gap-2 text-text-muted hover:text-text-main transition-colors mb-8 font-bold text-xs uppercase tracking-widest"
      >
        <ChevronLeft className="w-4 h-4" />
        New Analysis
      </button>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-12">
        <div className="lg:col-span-2 space-y-8">
          <div className="bento-card p-10">
            <div className="flex items-center justify-between mb-8">
              <h2 className="text-3xl font-bold text-text-main">Match Analysis</h2>
              <div className="flex flex-col items-end">
                <span className="text-[10px] font-bold text-text-muted uppercase tracking-widest mb-1">Match Score</span>
                <span className="text-5xl font-bold text-accent">{analysis.matchScore ?? 0}%</span>
              </div>
            </div>
            <p className="text-lg text-text-main leading-relaxed mb-8 border-l-4 border-accent pl-6 italic">
              "{analysis.feedback ?? "No feedback provided."}"
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bento-card border-success/20">
              <h3 className="text-sm font-bold text-text-main mb-6 flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-success" />
                Key Strengths
              </h3>
              <ul className="space-y-4">
                {strengths.length > 0 ? strengths.map((s: string, i: number) => (
                  <li key={i} className="text-sm text-text-muted flex gap-3">
                    <span className="text-success font-bold">•</span>
                    {s}
                  </li>
                )) : (
                  <li className="text-sm text-text-muted italic">No strengths identified.</li>
                )}
              </ul>
            </div>

            <div className="bento-card border-yellow-500/20">
              <h3 className="text-sm font-bold text-text-main mb-6 flex items-center gap-2">
                <AlertCircle className="w-4 h-4 text-yellow-500" />
                Critical Gaps
              </h3>
              <ul className="space-y-4">
                {gaps.length > 0 ? gaps.map((g: string, i: number) => (
                  <li key={i} className="text-sm text-text-muted flex gap-3">
                    <span className="text-yellow-500 font-bold">•</span>
                    {g}
                  </li>
                )) : (
                  <li className="text-sm text-text-muted italic">No gaps identified.</li>
                )}
              </ul>
            </div>
          </div>

          <div className="bento-card border-accent/20">
            <h3 className="text-sm font-bold text-text-main mb-6 flex items-center gap-2">
              <Lightbulb className="w-4 h-4 text-accent" />
              Recommended Improvements
            </h3>
            <div className="grid grid-cols-1 gap-4">
              {improvements.length > 0 ? improvements.map((imp: string, i: number) => (
                <div key={i} className="p-4 rounded-xl bg-accent/5 border border-accent/10 text-sm text-text-main leading-relaxed">
                  {imp}
                </div>
              )) : (
                <p className="text-sm text-text-muted italic">No improvements suggested.</p>
              )}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bento-card border-accent/20">
              <h3 className="text-sm font-bold text-text-main mb-6 flex items-center gap-2">
                <SpellCheck className="w-4 h-4 text-accent" />
                Spelling & Grammar
              </h3>
              <div className="space-y-3">
                {spellingFixes.length > 0 ? spellingFixes.map((fix: any, i: number) => (
                  <div key={i} className="flex flex-col gap-1 p-3 rounded-lg bg-red-500/5 border border-red-500/10">
                    <span className="text-[10px] text-red-500 line-through opacity-70 font-mono italic">"{fix.original}"</span>
                    <span className="text-sm text-text-main font-bold">Suggested: <span className="text-success underline">{fix.suggested}</span></span>
                  </div>
                )) : (
                  <p className="text-xs text-text-muted italic bg-success/5 border border-success/10 p-4 rounded-xl text-center">No spelling errors detected! ✨</p>
                )}
              </div>
            </div>

            <div className="bento-card border-accent/20">
              <h3 className="text-sm font-bold text-text-main mb-6 flex items-center gap-2">
                <LayoutList className="w-4 h-4 text-accent" />
                Formatting & Font
              </h3>
              <ul className="space-y-3">
                {formattingTips.length > 0 ? formattingTips.map((tip: string, i: number) => (
                  <li key={i} className="text-xs text-text-muted flex gap-3 leading-relaxed">
                    <span className="text-accent font-bold">•</span>
                    {tip}
                  </li>
                )) : (
                  <li className="text-xs text-text-muted italic">No formatting issues identified.</li>
                )}
              </ul>
            </div>
          </div>
        </div>

        <div className="space-y-8">
          <div className="bento-card">
            <h3 className="text-sm font-bold text-text-main mb-6 flex items-center gap-2">
              <Target className="w-4 h-4 text-accent" />
              Keyword Tracking
            </h3>
            
            <div className="space-y-6">
              <div>
                <p className="text-[10px] font-bold text-success uppercase tracking-widest mb-3">Found in Resume</p>
                <div className="flex flex-wrap gap-2">
                  {keywordsFound.length > 0 ? keywordsFound.map((k: string, i: number) => (
                    <span key={i} className="px-2 py-1 rounded-md bg-success/10 text-success text-[10px] font-bold uppercase border border-success/20">
                      {k}
                    </span>
                  )) : (
                    <span className="text-[10px] text-text-muted italic">None found.</span>
                  )}
                </div>
              </div>

              <div>
                <p className="text-[10px] font-bold text-red-500 uppercase tracking-widest mb-3">Missing from Resume</p>
                <div className="flex flex-wrap gap-2">
                  {keywordsMissing.length > 0 ? keywordsMissing.map((k: string, i: number) => (
                    <span key={i} className="px-2 py-1 rounded-md bg-red-500/10 text-red-500 text-[10px] font-bold uppercase border border-red-500/20">
                      {k}
                    </span>
                  )) : (
                    <span className="text-[10px] text-text-muted italic">None missing.</span>
                  )}
                </div>
              </div>
            </div>
          </div>

          <div className="bento-card bg-accent/10 border-accent/20">
            <h3 className="text-sm font-bold text-text-main mb-4">Next Steps</h3>
            <p className="text-xs text-text-muted mb-6 leading-relaxed">
              Based on this analysis, we recommend updating your resume with the missing keywords and addressing the identified gaps before applying.
            </p>
            <Button 
              onClick={handleExport}
              className="w-full bg-accent hover:bg-accent/90 rounded-xl h-12 font-bold text-xs uppercase tracking-widest"
            >
              <Download className="w-4 h-4 mr-2" />
              Export Feedback
            </Button>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
